services:
  # Backend API Service
  - type: web
    name: scaenahub-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: scaenahub-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GOOGLE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_PROJECT_ID
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: GOOGLE_DOCS_ID
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false

  # Frontend Static Site
  - type: static
    name: scaenahub-frontend
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://scaenahub-api.onrender.com/api
      - key: REACT_APP_SOCKET_URL
        value: https://scaenahub-api.onrender.com
      - key: REACT_APP_NAME
        value: ScaenaHub

databases:
  - name: scaenahub-db
    databaseName: scaenahub
    user: scaenahub_user
    plan: free